# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    
    - name: Restore dependencies
      run: nuget restore NetKiwi/NetKiwi/NetKiwi.csproj

    - name: Build
      run: |
        dotnet restore NetKiwi/NetKiwi/NetKiwi.csproj -r osx-x64
        dotnet build NetKiwi/NetKiwi/NetKiwi.csproj -r osx-x64
    
    - name: Test
      run: dotnet test NetKiwi/NetKiwi.Test/NetKiwi.Test.csproj
