# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET - linux
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    
    - name: Restore dependencies - linux
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt-get install libc6-dev
        nuget restore NetKiwi/NetKiwi/NetKiwi.csproj

    - name: Build - linux
      run: |
        dotnet restore NetKiwi/NetKiwi/NetKiwi.csproj -r linux-x64
        dotnet build NetKiwi/NetKiwi/NetKiwi.csproj -r linux-x64
    
    - name: Test  - linux
      run: dotnet test NetKiwi/NetKiwi.Test/NetKiwi.Test.csproj
