# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    
    - name: Restore dependencies
      run: nuget restore

    - name: Build
      run: |
        dotnet restore NetKiwi/NetKiwi/NetKiwi.csproj -r linux-x64
        dotnet build NetKiwi/NetKiwi/NetKiwi.csproj -r linux-x64
    
    - name: Test
      run: dotnet test NetKiwi/NetKiwi.Test/NetKiwi.Test.csproj
